version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: zabbix-postgres
    restart: always
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:6.0-ubuntu-latest
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_JAVA_GATEWAY: ""
      ZBX_JAVA_GATEWAY_PORT: "10052"
    ports:
      - "10051:10051"
    depends_on:
      - postgres
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:6.0-ubuntu-latest
    container_name: zabbix-web
    restart: always
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Manaus
    ports:
      - "8080:8080"
    networks:
      - zabbix-net
    depends_on:
      - zabbix-server

  # zabbix-agent:
  #   image: zabbix/zabbix-agent2:6.0-ubuntu-latest
  #   container_name: zabbix-agent
  #   restart: always
  #   environment:
  #     ZBX_SERVER_HOST: zabbix-server
  #     ZBX_HOSTNAME: zabbix-agent
  #     ZBX_SERVER_ACTIVE: zabbix-server
  #   ports:
  #     - "10050:10050"
  #   networks:
  #     - zabbix-net
  #   depends_on:
  #     - zabbix-server

networks:
  zabbix-net:
    driver: bridge